# Generated by Django 3.0.3 on 2022-01-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slider_title',
            new_name='slider_title1',
        ),
    ]
