# Generated by Django 3.0.3 on 2022-01-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20220124_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_title2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_title1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
