# Generated by Django 3.0.3 on 2022-01-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image_full', models.ImageField(upload_to='gallery/%Y/%m/%d/')),
                ('gallery_thumbnail', models.ImageField(upload_to='gallery/%Y/%m/%d/')),
                ('gallery_image_title', models.CharField(max_length=200)),
                ('gallery_image_description', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
