# Generated by Django 3.0.3 on 2022-01-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='galery_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_galery_graphic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_galery_icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_galery_web',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
