# Generated by Django 3.0.3 on 2022-01-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20220125_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='is_galery_graphic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_galery_icon',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_galery_web',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
