# Generated by Django 3.0.3 on 2022-01-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20220125_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='is_galery_graphic',
            new_name='is_galery_data_type_graphic',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='is_galery_icon',
            new_name='is_galery_data_type_icon',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='is_galery_web',
            new_name='is_galery_data_type_web',
        ),
        migrations.AddField(
            model_name='category',
            name='category_class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
