# Generated by Django 3.0.3 on 2022-01-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_gallery_is_galery_data_type_webdev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='is_galery_data_type_graphic',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_galery_data_type_icon',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_galery_data_type_web',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_galery_data_type_webdev',
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_data_type',
            field=models.CharField(choices=[('webdesign', 'webdesign'), ('webdev', 'webdev'), ('icon', 'icon'), ('graphic', 'graphic')], default='webdesign', max_length=30),
        ),
    ]
